### ISSUE TITLE
Does this work with autodiff?

### ISSUE THREAD

**Issue by alok** [eschnett/DifferentialForms.jl#7]
Grassmann does not and that led me here

**Comment by chakravala** [comment]
@alok you are mistaken, [Grassmann.jl](https://github.com/chakravala/Grassmann.jl) does support automatic differentiation, in fact it has built in support for it. It is not intended to be used with with Flux, you want to use it. It is intended to be its own automatic differentiation library.

Just because you cant combine Grassmann with Flux the way you want, doesnt mean it does not do automatic differentiation, this is plainly false as Grassmann has its own AD design built in.

**Comment by eschnett** [comment]
@alok It should. Are you referring to a particular autodiff package? I have used `ForwardDiff.jl` myself in the past, but not e.g. `ReverseDiff.jl`. Do you have a particular example in mind?

If there's a particular thing that is missing or that stands in the way of automatic differentiation I'd be happy to update the package.

**Comment by alok** [comment]
@chakravala how does one use grassmann’s AD?

**Comment by chakravala** [comment]
I dont like to discuss the more experimental aspects of my research publicly on another (rival) repository

**Comment by alok** [comment]
Is this information publicly available in general?

**Comment by chakravala** [comment]
It's no longer my concern whether anything I do is publicly understood, my source code is out there for those bold enough to research it and documented enough for those who want to reach out to me with some kind of research grant collaboration.

You work for the military with practically unlimited budged, but you can't get funding for the work you're taking from other people?

**Comment by alok** [comment]
> It's no longer my concern whether anything I do is publicly understood

False. You _are_ concerned. Otherwise, why would you correct my misunderstanding about grassmann's AD support if you didn't see it as your concern? 

I work for the department of energy, not the military.

**Comment by eschnett** [comment]
The discussion here is getting off-topic, so I am closing this issue. @alok, if you want to discuss auto-differentiation, could you open a new issue?
